### ISSUE TITLE
字体文件下载链接失效

### ISSUE THREAD

**Issue by Volcano-Yang** [junbin123/likeday#2]
![image](https://user-images.githubusercontent.com/43328103/112484740-2c7e3e00-8db5-11eb-84e6-4c3636bfba15.png)

这个字体文件下载链接已经挂了。

**Comment by junbin123** [comment]
项目我用 uni-app 框架重构了，字体链接：https://6c69-likeday-f4b2b-1300778416.tcb.qcloud.la/font/LikeDayFont.woff2
